### Staging Auto-Deploy
auto_deploy_staging: True
initial_image: public.ecr.aws/adelagon/flask-app:latest

### Static Application Security Testing (SAST) Step
sast:
  enabled: True
  sonarqube:
    image: public.ecr.aws/adelagon/sonarqube:lts-community
    token: 24d6fb4c70421327d2b6d61d47be291c2308102f

### Software Composition Analysis (SCA) Step
sca:
  enabled: True

### License Checker Step
license:
  enabled: True

### Dynamic Application Security Testing (DAST) Step
dast:
  enabled: True
  zaproxy:
    instance_type: t3.medium
    api_key: SomeRandomString